// ── Notification setting constants (no "use server" — safe to import anywhere) ──

export const NOTIFICATION_FROM_EMAIL = 'noreply@sarmalinux.com'

export const EMAIL_NOTIFICATION_KEYS = [
    "email_leave_submitted",
    "email_leave_approved",
    "email_leave_rejected",
    "email_leave_withdrawn",
    "email_wfh",
    "email_early_clockout",
    "email_running_late",
    "email_forgotten_clockout",
    "email_birthday",
    "email_birthday_self",
    "email_correction_submitted",
    "email_correction_reviewed",
    "email_expense_submitted",
    "email_expense_approved",
    "email_expense_rejected",
    "email_purchase_request_submitted",
    "email_purchase_request_decision",
    "email_announcement",
    "email_poll_created",
    "email_absent_reminder",
    "email_missing_attendance",
    "email_it_ticket_submitted",
    "email_it_ticket_status",
    "email_it_ticket_comment",
    "email_wellness_event",
    "email_bank_statement_unmatched",
    "email_jarvis_issue_report",
] as const

export type EmailNotificationKey = typeof EMAIL_NOTIFICATION_KEYS[number]

export const EMAIL_NOTIFICATION_META: Record<EmailNotificationKey, {
    label: string
    description: string
    detail: string
    group: string
    recipient: string
    subject: string
    trigger: string
}> = {
    email_leave_submitted: {
        label: "Leave Request Submitted",
        description: "Sent when an employee submits a leave request.",
        detail: "Two separate emails are sent: (1) Employee receives \"Your leave request has been submitted\" with their dates and remaining balance. (2) Their designated approver receives \"Action Required: Leave Request from [Name]\" with full details and a link to the Approvals page to approve or reject.",
        group: "Leave",
        recipient: "Employee (confirmation) + Approver (action required) — separate emails",
        subject: "Leave Request Submitted — {Leave Type} ({Start} to {End})",
        trigger: "When employee clicks Submit on the leave form",
    },
    email_leave_approved: {
        label: "Leave Approved",
        description: "Sent when an approver approves a leave request.",
        detail: "Two separate emails are sent: (1) Employee receives \"Your leave has been approved\" with their dates, approver name, and updated leave balance. (2) Accounts team receives full leave details so they can update payroll records.",
        group: "Leave",
        recipient: "Employee (approval confirmation) + Accounts team (payroll copy)",
        subject: "Leave Approved — {Leave Type} ({Start} to {End})",
        trigger: "When approver clicks Approve on the Approvals page",
    },
    email_leave_rejected: {
        label: "Leave Declined",
        description: "Sent when an approver rejects a leave request.",
        detail: "Employee receives \"Your leave request has been declined\" with the rejection reason provided by their manager, their original dates, and their current leave balance. Approver does not receive a copy.",
        group: "Leave",
        recipient: "Employee only",
        subject: "Leave Request Declined — {Leave Type} ({Start} to {End})",
        trigger: "When manager clicks Reject and confirms a reason on the Approvals page",
    },
    email_leave_withdrawn: {
        label: "Leave Withdrawn",
        description: "Sent when an employee withdraws a pending or approved leave request.",
        detail: "When an employee withdraws leave, a single notification email is sent to the approver (if one was assigned) and accounts@yourcompany.com. The email includes the employee name, leave type, dates, and number of days returned to their balance. The withdrawing employee does not receive an email. The request is kept in the database as withdrawn — it is never deleted. Both the employee and accounts can download a withdrawal record PDF (marked WITHDRAWN in amber, for audit reference only). Withdrawn records are visible in the admin Leave Records page alongside approved records.",
        group: "Leave",
        recipient: "Approver (if assigned) + accounts@yourcompany.com",
        subject: "Leave Withdrawn — {Employee Name} ({Leave Type}, {Date Range})",
        trigger: "When employee clicks Withdraw on a pending or approved request on their Leave page",
    },
    email_wfh: {
        label: "WFH Notification",
        description: "Sent when an employee enables Work From Home for the day.",
        detail: "Reception/office group inbox receives \"Working From Home - [Name]\" with the employee's name, department, date, WFH type (full day / half AM / half PM), and any reason provided. Useful for front-of-house awareness.",
        group: "Attendance",
        recipient: "memofashions@yourcompany.com",
        subject: "{Employee Name} is Working From Home on {Date}",
        trigger: "When employee enables WFH toggle on their home page",
    },
    email_early_clockout: {
        label: "Early Departure",
        description: "Sent when an employee clocks out early using the Early Leave feature.",
        detail: "Office group inbox receives \"Early Departure Notice\" with the employee's name, department, clock-out time, hours worked, and the reason they provided. Helps management track early departures in real time.",
        group: "Attendance",
        recipient: "memofashions@yourcompany.com",
        subject: "Early Departure — {Employee Name} on {Date}",
        trigger: "When employee submits an early clock-out with a reason",
    },
    email_running_late: {
        label: "Running Late",
        description: "Sent when an employee reports they are running late to the office.",
        detail: "Office group inbox receives \"Running Late - [Name]\" with the employee's name, department, expected arrival time, and reason. Can be triggered by the employee themselves or logged by Reception on their behalf.",
        group: "Attendance",
        recipient: "memofashions@yourcompany.com",
        subject: "Running Late — {Employee Name}",
        trigger: "Employee clicks I'm Running Late, or Reception logs a late arrival on the Reception page",
    },
    email_forgotten_clockout: {
        label: "Forgotten Clock-out Reminder",
        description: "Sent Mon-Fri at 7pm if an employee clocked in but never clocked out.",
        detail: "Two separate emails are sent: (1) Employee receives a personal reminder \"You forgot to clock out today\" with their clock-in time and a direct link to submit a correction. (2) Reception receives a separate alert \"Missed Clock-out - [Name]\" so they are aware. Only fires once per employee per day — no duplicate alerts. Automatically skips UK bank holidays.",
        group: "Attendance",
        recipient: "Employee + reception@yourcompany.com",
        subject: "Reminder: You forgot to clock out on {Date}",
        trigger: "Mon-Fri at 7pm UK time — automated check for missing clock-out (skips bank holidays)",
    },
    email_birthday: {
        label: "Birthday Reminder (to colleagues)",
        description: "Sent 2 days before a colleague's birthday so staff can prepare.",
        detail: "All active employees (except the birthday person) receive a reminder so they have time to sign a card or organise a surprise. Runs daily at 8am via GitHub Actions.",
        group: "People",
        recipient: "All active employees (except birthday person)",
        subject: "It's {Name}'s Birthday Soon!",
        trigger: "Daily at 8am — 2 days before an employee's birthday",
    },
    email_birthday_self: {
        label: "Birthday Wish (to birthday person)",
        description: "Sends a personal Happy Birthday message to the employee on their birthday.",
        detail: "The birthday employee receives a warm personal email addressed to them by name, sent on the morning of their birthday. Runs daily at 8am via GitHub Actions.",
        group: "People",
        recipient: "Birthday person only",
        subject: "Happy Birthday from Your Companys!",
        trigger: "Daily at 8am on the employee's birthday",
    },
    email_correction_submitted: {
        label: "Correction Request Received",
        description: "Sent to reception when an employee submits an attendance correction.",
        detail: "Reception inbox receives \"Correction Request - [Employee]\" with the employee's name, the field being corrected (e.g. clock_in), the original value, the proposed new value, and the date. Reception or admin can then approve or reject it from the Approvals page.",
        group: "Corrections",
        recipient: "reception@yourcompany.com",
        subject: "Correction Request — {Employee} · {Field} on {Date}",
        trigger: "When an employee submits a correction request",
    },
    email_correction_reviewed: {
        label: "Correction Decision",
        description: "Sent to the employee when their correction is approved or rejected.",
        detail: "Employee receives \"Correction Approved\" or \"Correction Rejected\" with the field, original value, the new applied value (if approved), and the reviewer's name. Keeps employees informed without needing to check the app.",
        group: "Corrections",
        recipient: "Employee only",
        subject: "Correction {Approved/Rejected} — {Field} on {Date}",
        trigger: "When admin or reception approves or rejects a correction on the Approvals page",
    },
    email_expense_submitted: {
        label: "Expense Submitted",
        description: "Sent to the first approver when an expense claim is submitted.",
        detail: "Approver receives \"Action Required: Expense Claim from [Name]\" with the employee's name, amount, currency, merchant, date, description, and a direct link to the Approvals tab in Expense Manager. If auto-approve is enabled for that user, no email is sent.",
        group: "Expenses",
        recipient: "First approver in the chain",
        subject: "Action Required: Expense Claim from {Employee Name}",
        trigger: "When an employee submits an expense claim",
    },
    email_expense_approved: {
        label: "Expense Approved",
        description: "Sent when an expense is fully approved at all steps.",
        detail: "For personal card / cash claims: (1) Employee receives \"Your Expense Has Been Approved\" with a direct link to download their claim form PDF. (2) Every user with the Accounts role receives \"New Expense Claim to Reimburse\" with the employee name, amount, and a link to download the claim form PDF to process reimbursement. For company card / cash withdrawal expenses: only the employee receives a confirmation — no accounts notification as no personal money is involved.",
        group: "Expenses",
        recipient: "Employee (confirmation + claim form link). Accounts team (reimbursement notification + claim form link) — personal claims only.",
        subject: "Your Expense Has Been Approved / New Expense Claim to Reimburse",
        trigger: "When the final approver in the chain approves the expense",
    },
    email_expense_rejected: {
        label: "Expense Rejected",
        description: "Sent to the employee when their expense is rejected at any step.",
        detail: "Employee receives \"Your Expense Could Not Be Approved\" with the rejection reason provided by the approver, the original amount and description, and a link to resubmit with more information.",
        group: "Expenses",
        recipient: "Employee only",
        subject: "Your Expense Could Not Be Approved",
        trigger: "When an approver rejects an expense at any step in the chain",
    },
    email_purchase_request_submitted: {
        label: "Purchase Request Submitted",
        description: "Sent to the approver when a purchase request is submitted.",
        detail: "Approver receives \"Purchase Request: [Item] — Action Required\" with the item name, estimated cost, urgency level (colour-coded: Low/Medium/High), justification text, and a link to approve or reject in Expense Manager.",
        group: "Expenses",
        recipient: "Approver (Line Manager / Director)",
        subject: "Purchase Request: {Item Name} — Action Required",
        trigger: "When an employee submits a purchase request",
    },
    email_purchase_request_decision: {
        label: "Purchase Request Decision",
        description: "Sent to the employee when their purchase request is approved or rejected.",
        detail: "Employee receives \"Purchase Request Approved: [Item]\" or \"Purchase Request Not Approved: [Item]\" with the item name, any note from the approver, and a link to view the request.",
        group: "Expenses",
        recipient: "Employee only",
        subject: "Purchase Request {Approved/Not Approved}: {Item Name}",
        trigger: "When an approver makes a decision on a purchase request",
    },
    email_announcement: {
        label: "Staff Announcement",
        description: "Sent when any staff member sends a broadcast announcement.",
        detail: "A branded email is sent to memofashions@yourcompany.com — the company group inbox — from noreply@sarmalinux.com. The email includes the subject, full message body, and optionally a calendar event card with a .ics file attachment. Recipients can click the attachment to add the event directly to Outlook, Google Calendar, or Apple Calendar. All sent announcements are logged in Nexus.",
        group: "Announcements",
        recipient: "memofashions@yourcompany.com (all staff group inbox)",
        subject: "📢 {Announcement Subject}",
        trigger: "When any staff member sends an announcement from the Announcements page",
    },
    email_poll_created: {
        label: "New Poll Created",
        description: "Sent to all staff (except Directors) when someone creates a new poll.",
        detail: "All active employees except those with the Director role receive an email with the poll question, the available options, the deadline, and a direct link to vote in Nexus. Directors are excluded from poll emails by design.",
        group: "Polls",
        recipient: "All active staff (excluding Directors)",
        subject: "📊 New Poll: {Poll Question}",
        trigger: "When any staff member creates a new poll on the Polls page",
    },
    email_it_ticket_submitted: {
        label: "IT Ticket Submitted",
        description: "Sent to the IT admin when a new support ticket is raised.",
        detail: "The IT admin receives an email with the full ticket details including category, priority, and description, plus a direct link to the IT Admin Portal in Nexus to start working on it.",
        group: "IT Support",
        recipient: "IT Admin",
        subject: "[IT #123] {Ticket Title}",
        trigger: "When any staff member submits a new IT support ticket",
    },
    email_it_ticket_status: {
        label: "IT Ticket Status Update",
        description: "Sent to the submitter when their ticket status changes.",
        detail: "The ticket submitter receives a notification whenever the IT admin changes the ticket status (Open, In Progress, Resolved, Closed). The email includes a clear message explaining what the status change means and a link to view their tickets.",
        group: "IT Support",
        recipient: "Ticket submitter",
        subject: "[IT #123] Status: {New Status}",
        trigger: "When admin changes a ticket status",
    },
    email_it_ticket_comment: {
        label: "IT Ticket Reply",
        description: "Sent to the submitter when the IT admin adds a reply to their ticket.",
        detail: "The ticket submitter receives an email quoting the reply message so they can read it without opening Nexus. Non-internal comments only — internal admin notes are never sent to the submitter.",
        group: "IT Support",
        recipient: "Ticket submitter",
        subject: "[IT #123] New reply: {Ticket Title}",
        trigger: "When admin posts a public reply on a ticket",
    },
    email_wellness_event: {
        label: "New Wellness Event",
        description: "Sent to all staff when a new wellness event is created.",
        detail: "All active staff receive a notification about the new event including the date, time, location, and organiser. Each user can disable this notification in their Wellness Hub preferences. Directors are included by default.",
        group: "Wellness",
        recipient: "All active staff",
        subject: "Wellness Event: {Event Title} on {Date}",
        trigger: "When any staff member creates a wellness event",
    },
    email_absent_reminder: {
        label: "Absent Reminder",
        description: "Sent at 10am Mon–Fri to staff who haven't clocked in and have no absence accounted for.",
        detail: "At 10am every weekday, the system checks all active staff (excluding Directors and users with 'Exclude from reminders' flag). Respects work schedules — only staff scheduled to work today are checked. Anyone who has not clocked in AND has no approved holiday, no calendar leave, no WFH logged, and no running-late flag receives a reminder. Automatically skips UK bank holidays (checked via gov.uk API with hardcoded fallback).",
        group: "Attendance",
        recipient: "Individual staff member (personal email)",
        subject: "You haven't clocked in today",
        trigger: "Mon–Fri at 10am UK time — automated check for unaccounted absences (skips bank holidays, respects work schedules)",
    },
    email_missing_attendance: {
        label: "Missing Attendance Report",
        description: "Sent at 7pm Mon–Fri to flag staff with no attendance record for the day.",
        detail: "At 7pm every weekday, the system checks all active staff (excluding Directors and users with 'Exclude from reminders' flag). Respects work schedules — only staff scheduled to work today are checked. Anyone who has no clock-in, no approved leave, no calendar leave, and no WFH logged receives a personal email asking them to update their record (annual leave, sick leave, or speak to reception). A separate summary email is sent to accounts@yourcompany.com so they can follow up before payroll. Automatically skips UK bank holidays.",
        group: "Attendance",
        recipient: "Individual staff member + Accounts team (accounts@yourcompany.com)",
        subject: "Attendance Record Missing — {Date}",
        trigger: "Mon–Fri at 7pm UK time — automated check for completely missing records (skips bank holidays, respects work schedules)",
    },
    email_bank_statement_unmatched: {
        label: "Bank Statement — Missing Receipts",
        description: "Sent manually to the cardholder when an admin clicks the mail icon on a statement card.",
        detail: "When an admin clicks the mail icon on a bank statement card, a manual email is sent to the cardholder listing transactions with no receipt uploaded. The email includes step-by-step instructions to open each [Receipt needed] stub in Nexus, upload the receipt, and save. No one else receives this email — only the cardholder.",
        group: "Expenses",
        recipient: "Cardholder only (matched by card's last 4 digits)",
        subject: "[StaffPortal] Please upload receipts for your company card — {Month Year}",
        trigger: "Manual — admin clicks the mail icon on a statement card",
    },
    email_jarvis_issue_report: {
        label: "Jarvis — Issue Report",
        description: "Sent to admin when a user reports a bug or problem through the Jarvis chatbot.",
        detail: "When a user tells Jarvis about a problem (e.g. 'the calendar isn't loading', 'my leave balance is wrong'), Jarvis collects the details through conversation and sends a formatted report to the admin. Includes the user's name, email, and full description of the issue.",
        group: "System",
        recipient: "Admin (sai@yourcompany.com)",
        subject: "[Jarvis] Issue reported by {User Email}",
        trigger: "Automatic — when Jarvis detects an issue report in conversation and has collected enough details",
    },
}
